sudo: required
services:
    - docker

before_install:
    - docker build -t raghavendranataraj/docker-react -f Dockerfile.dev .

script:
    - docker run raghavendranataraj/docker-react npm run test -- --coverage

